# Generated by Django 5.2.9 on 2026-02-16 18:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DifferentBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('published_date', models.DateField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_published', models.BooleanField(default=False, verbose_name='منتشر شده')),
                ('name', models.CharField(max_length=200)),
                ('author', models.CharField(blank=True, max_length=100)),
                ('published_date', models.DateField(blank=True, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('category', models.CharField(choices=[('SC', 'Science'), ('FN', 'Fun'), ('HC', 'Historical'), ('RM', 'Romance'), ('TH', 'Thriller')], default='FN', max_length=2)),
                ('currency', models.CharField(choices=[('TOMAN', 'Toman'), ('USD', 'US Dollar')], default='TOMAN', max_length=5)),
                ('page_count', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('publisher_name', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('publisher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='books', to=settings.AUTH_USER_MODEL, verbose_name='ناشر')),
            ],
        ),
        migrations.CreateModel(
            name='ImageBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Image Name')),
                ('image', models.ImageField(blank=True, null=True, upload_to='book_images/', verbose_name='تصویر')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', related_query_name='image_query', to='book.book')),
            ],
            options={
                'verbose_name': 'Images of Book',
            },
        ),
    ]
