# Generated by Django 5.2.9 on 2026-02-24 10:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='APILearningLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(verbose_name='آدرس IP')),
                ('method', models.CharField(max_length=10, verbose_name='متد HTTP')),
                ('url', models.URLField(verbose_name='آدرس')),
                ('status_code', models.PositiveIntegerField(verbose_name='کد وضعیت')),
                ('response_time_ms', models.FloatField(verbose_name='زمان پاسخ (میلی\u200cثانیه)')),
                ('is_slow', models.BooleanField(default=False, verbose_name='آیا کند بود؟')),
                ('user_agent', models.TextField(blank=True, verbose_name='مرورگر')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_logs', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'لاگ آموزشی API',
                'verbose_name_plural': 'لاگ\u200cهای آموزشی API',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_at'], name='book_apilea_created_8bea0f_idx'), models.Index(fields=['is_slow'], name='book_apilea_is_slow_3dc530_idx'), models.Index(fields=['user'], name='book_apilea_user_id_9123d7_idx')],
            },
        ),
    ]
