# Generated by Django 5.2.9 on 2025-12-23 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='currency',
            field=models.CharField(choices=[('TOMAN', 'Toman'), ('USD', 'US Dollar')], default='TOMAN', max_length=5),
        ),
    ]
