# Generated by Django 5.2.9 on 2026-02-11 21:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_alter_book_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='DifferentBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('published_date', models.DateField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ImageBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Image Name')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', related_query_name='image_query', to='book.book')),
            ],
            options={
                'verbose_name': 'Images of Book',
            },
        ),
    ]
